### ISSUE TITLE
[UI Issues]

### ISSUE THREAD

**Issue by TartejBrothers** [ashiqee/event-management-react-project#1]
# Issues
- The spelling for Sign Up is wrong in the events page. It says Sing up with Google 
![image](https://github.com/ashiqee/event-management-react-project/assets/112921727/98248205-e740-43c2-9386-59a4863a39ab)

# UI changes : 
- Add some padding at the bottom of the speakers.
![image](https://github.com/ashiqee/event-management-react-project/assets/112921727/be778ffd-f2ed-4186-9317-413af36fa8fc)

**Comment by notajax24** [comment]
Can i work on this issue?

**Comment by TartejBrothers** [comment]
These have been fixed by the developer
